retreive list of projects from redcap
research-resource/research_resource pull request #136
Opened 2017-04-04 13:34 UTC by SimonLab

Get name and description of the projects for /projects endpoint.

Project on Redcap must follow a convention.
- The name of the instrument (form) must start with "project:"
- a "name" field must be defined with the name value define in the annotation field
- a "description" field must be defined with the description value in the annotation field

2017-04-04 15:33 UTC, Danwhy approved these changes
LGTM

2017-04-04 16:33 UTC, samhstn requested changes
@SimonLab Let me know about my comment.
Let me know if you would like me to have a go at it

2017-04-04 16:33 UTC, samhstn commented on web/templates/projects/index.html.eex
> +    <% end %>
Great idea 👍

2017-04-04 16:33 UTC, shouston3 commented on web/controllers/redcap/http_client.ex
> +        true ->
@SimonLab could you have a go at tidying up this section, it seems a bit hard to read.
Perhaps abstract out some of the logic
Also I think the:
```elixir
!Bool && (Bool || Bool)
```
pattern is a little hard to read

2017-04-05 12:19 UTC, SimonLab commented
Thanks for the review, @shouston3 I've tried to simplify how we extract the data from Redcap for the projects. Do you mind to have a look at it again? Thanks

2017-04-05 13:29 UTC, shouston3 commented
Quick question, why are we ignoring the [`web/controllers/redcap/http_client.ex`](https://github.com/research-resource/research_resource/blob/master/coveralls.json#L12) and `web/controllers/qualtrics/http_client.ex` files.

Refactoring may be easier if we have tests for these functions

2017-04-05 13:33 UTC, merged

2017-04-05 13:35 UTC, SimonLab commented
We are using ```web/controllers/redcap/in_memory.ex``` for the tests so we never call the the http_client. But we can maybe extract the "helper" functions in http_client in the helpers file, I will create an new issue for that, thanks