check if survey already completed
research-resource/research_resource pull request #71
Opened 2017-03-23 13:54 UTC by SimonLab

see #67

This PR add a new migration, so don't forget to run ```mix ecto.migrate``` before running the application

2017-03-23 14:32 UTC, samhstn reviewed
Looks good 👍 

I'm easy about if you want to implement these stylistic changes or not

2017-03-23 14:32 UTC, shouston3 commented on test/controllers/qualtrics_controller_test.exs
> +      end
Could you take out the common parts of the if/else:

```elixir
if username == "survey@completed.com" do
  user = insert_user(%{email: username, qualtrics_id: "1"})
else
  user = insert_user(%{email: username})
end
conn = assign(build_conn(), :current_user, user)
{:ok, conn: conn, user: user}
```
I find it a little easier to read

2017-03-23 14:32 UTC, shouston3 commented on web/controllers/consent_controller.ex
> +  alias ResearchResource.User
`alias ResearchResource.{Redcap.RedcapHelpers, Qualitrics.QualtricsHelpers, User}`
I prefer this shorter syntax
Not a big deal though

2017-03-23 14:32 UTC, shouston3 commented on web/controllers/qualtrics/http_client.ex
> +    url = "#{@qualtrics_url}/distributions/#{@qualtrics_distribution_id}/links?surveyId=#{@qualtrics_survey_id}"
nice 👍

2017-03-23 14:32 UTC, shouston3 commented on web/controllers/qualtrics/http_client.ex
> +        survey_history = List.first(Enum.filter(contact["responseHistory"], fn(history) -> history["surveyId"] == @qualtrics_survey_id end))
I would prefer to read something like:
```elixir
survey_history
=  contact["responseHistory"]
|> Enum.filter(&(&1["surveyId"] == @qualtrics_survey_id])
|> List.first
```
but again, not a big deal

2017-03-23 14:41 UTC, SimonLab commented on test/controllers/qualtrics_controller_test.exs
> +      end
My  code was similar but Elixir warn me to not use variable created in a scope outside of the scope:
![warning-user](https://cloud.githubusercontent.com/assets/6057298/24252898/b5b9062a-0fd6-11e7-8552-123164cc6476.png)

But agree I think there is a better way to do this.

2017-03-23 14:55 UTC, shouston3 commented on test/controllers/qualtrics_controller_test.exs
> +      end
```elixir
%{email: username}
|> Map.merge(if username == "survey@completed.com" do %{qualtrics_id: "1"} else %{} end)
|> insert_user

conn = assign(build_conn(), :current_user, user)
{:ok, conn: conn, user: user}
```

Might work

2017-03-23 15:55 UTC, samhstn requested changes
Minor syntax points, otherwise all good 👍

2017-03-24 11:17 UTC, SimonLab commented
Thanks for the review @shouston3 I've just added your changes, do you mind to have a look at the PR again?

2017-03-24 11:27 UTC, samhstn requested changes

2017-03-24 11:27 UTC, shouston3 commented on web/controllers/consent_controller.ex
> +  alias ResearchResource.{Redcap.RedcapHelpers, Qualtrics.QualtricsHelpers, User}
You missed deleting the above aliases

2017-03-24 11:54 UTC, SimonLab commented on web/controllers/consent_controller.ex
> +  alias ResearchResource.{Redcap.RedcapHelpers, Qualtrics.QualtricsHelpers, User}
@shouston3 fixed with https://github.com/research-resource/research_resource/pull/71/commits/1962b2fccc21a17eddcfb283b558880fe6ddba3e

2017-03-24 11:55 UTC, SimonLab commented
@shouston3 fixed see https://github.com/research-resource/research_resource/pull/71#discussion_r107886668

2017-03-24 12:02 UTC, samhstn approved these changes
Looks good, over to you @Danwhy

2017-03-24 12:12 UTC, Danwhy approved these changes
LGTM 👍

2017-03-24 12:12 UTC, merged