Profile
research-resource/research_resource pull request #72
Opened 2017-03-23 20:18 UTC by Danwhy

Adds profile page and links it with redcap, enabling users to see and update their info
ref #35

2017-03-23 20:33 UTC, samhstn requested changes

2017-03-23 20:33 UTC, shouston3 commented on web/controllers/account_controller.ex
> +        |> redirect(to: account_path(conn, :index))
Love this 👍

2017-03-23 20:33 UTC, shouston3 commented on web/controllers/account_controller.ex
> +      {atom_key, val} = {String.to_atom(key), val}
Maybe this bit can be tidied up a little
```elixir
Enum.map(fn {key, val} -> {String.to_atom(key), val} end)
```

2017-03-23 20:33 UTC, samhstn requested changes
Minor syntax point, but all good

So nice to read through @Danwhy 👍

2017-03-23 20:40 UTC, Danwhy commented
Thanks @shouston3, I've added your suggestion

2017-03-23 20:47 UTC, samhstn approved these changes
Looks good, over to you @SimonLab

2017-03-23 20:47 UTC, shouston3 commented on web/controllers/account_controller.ex
> +    |> Enum.map(fn {key, val} -> {String.to_atom(key), val} end)
I'm fine if you don't want to implement this, but my personal preference would be:
```elixir
user_details =
  conn.assigns.current_user.ttrrid
  |> @redcap_api.get_user_data
  |> Enum.to_list
  |> Enum.map(fn {key, val} -> {String.to_atom(key), val} end)
```

Just so it is consistent how we are applying the functions

But if you would prefer to leave this, that's good with me

2017-03-24 09:52 UTC, Danwhy commented on web/controllers/account_controller.ex
> +    |> Enum.map(fn {key, val} -> {String.to_atom(key), val} end)
No I agree, your way looks much nicer

2017-03-24 10:34 UTC, SimonLab approved these changes
Looks good, thanks @shouston3 for the review

2017-03-24 10:34 UTC, merged